//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Information.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public string Designation { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<bool> IsBonusAdded { get; set; }
    }
}
