//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Information.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BSEntities : DbContext
    {
        public BSEntities()
            : base("name=BSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Manager> Managers { get; set; }
    
        public virtual ObjectResult<Employee_Info_Result> Employee_Info(Nullable<int> p_EmployeeId)
        {
            var p_EmployeeIdParameter = p_EmployeeId.HasValue ?
                new ObjectParameter("p_EmployeeId", p_EmployeeId) :
                new ObjectParameter("p_EmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Employee_Info_Result>("Employee_Info", p_EmployeeIdParameter);
        }
    }
}
